# Generated by Django 2.2.6 on 2019-10-16 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survivor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'FEMALE')], max_length=1)),
                ('infected', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Survivor',
                'verbose_name_plural': 'Survivors',
            },
        ),
        migrations.CreateModel(
            name='LastLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('survivor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='last_location', to='zssn.Survivor')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water', models.IntegerField(default=0)),
                ('food', models.IntegerField(default=0)),
                ('med', models.IntegerField(default=0)),
                ('ammo', models.IntegerField(default=0)),
                ('survivor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='zssn.Survivor')),
            ],
            options={
                'verbose_name': 'Inventory',
                'verbose_name_plural': 'Inventories',
            },
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flagged', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flagged', to='zssn.Survivor')),
                ('flagging', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flagging', to='zssn.Survivor')),
            ],
        ),
    ]
