# Generated by Django 2.2.6 on 2019-10-16 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zssn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='survivor',
            name='gender',
            field=models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=1),
        ),
        migrations.DeleteModel(
            name='LastLocation',
        ),
        migrations.AddField(
            model_name='location',
            name='survivor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='zssn.Survivor'),
        ),
    ]
